/* Amplify Params - DO NOT EDIT
	API_CAAKMN_COMMENTTOTALTABLE_ARN
	API_CAAKMN_COMMENTTOTALTABLE_NAME
	API_CAAKMN_GRAPHQLAPIIDOUTPUT
	API_CAAKMN_GROUPTOTALTABLE_ARN
	API_CAAKMN_GROUPTOTALTABLE_NAME
	API_CAAKMN_POSTITEMSTABLE_ARN
	API_CAAKMN_POSTITEMSTABLE_NAME
	API_CAAKMN_POSTTOTALTABLE_ARN
	API_CAAKMN_POSTTOTALTABLE_NAME
	API_CAAKMN_USERTOTALTABLE_ARN
	API_CAAKMN_USERTOTALTABLE_NAME
	ENV
	REGION
Amplify Params - DO NOT EDIT */

exports.handler = async (event) => {
	console.log(event.arguments)
    return event.arguments
};
